# Generated by Django 2.2.19 on 2021-02-23 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210223_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
